steps:
    - name: '$_DOCKER_REGISTRY/chanux/hugo:0.145.0'
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '-r', 'public/*', 'gs://$_GCS_BUCKET_NAME/blog']
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', 'homepage/*', 'gs://$_GCS_BUCKET_NAME/']
