steps:
    - name: 'asia.gcr.io/$PROJECT_ID/hugo'
      args: ['version']
    - name: gcr.io/cloud-builders/git
      args:
          - clone
          - --depth=1
          - --branch=master
          - --single-branch
          - https://github.com/digitalcraftsman/hugo-cactus-theme.git
          - themes/cactus-x
    - name: 'asia.gcr.io/$PROJECT_ID/hugo'
      args: ['--theme', 'cactus-x']
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '-r', 'public/*', 'gs://$_GCS_BUCKET_NAME/blog']
