steps:
    - name: 'asia.gcr.io/$PROJECT_ID/hugo'
      args: ['version']
    - name: 'asia.gcr.io/$PROJECT_ID/hugo'
      args: ['--verbose']
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '-r', 'public/*', 'gs://$_GCS_BUCKET_NAME/blog']
