baseurl = "https://chanux.me/blog/"
title   = "Chanux"
theme   = "mini"

canonifyurls = true

[params]
    author  = "Chanux"
    bio     = "I am nothing"

    twitter     = "chanux"
    enableRSS   = true
    showPowerBy = false

[social]
    twitter = "https://www.twitter.com/chanux"
    github  = "https://www.github.com/chanux"
